### PR TITLE
Wrap documents returned by `request`

### PR DESCRIPTION
**Pull request by AbeJellinek**
To mimic the behavior of `processDocuments`.

### CODE REVIEW

**Comment by AbeJellinek** [comment]
Right, I see. The problem is that `Zotero.HTTP.request` returns a promise that just resolves to a plain XHR object. `XMLHttpRequest.response` is read only, so we can't have `request` update it with a wrapped document, and I'd rather not build a fake XHR-like object if we can avoid it - I'm not sure an XHR-*like* object is good enough for every caller. Solutions for this problem are [very hacky](https://stackoverflow.com/questions/26447335/how-can-i-modify-the-xmlhttprequest-responsetext-received-by-another-function).

So I don't think we can reasonably assume that the XHR object returned by `request` will have a wrapped document in the response. It's not worth adding a hack to a core HTTP method in order to fake a browser document when so few call sites need one.

Would it be an alright workaround if I just added a dependency-free wrapping routine here? It would duplicate code from the client repo slightly but would, I think, be the best solution.

**Comment by adomasven** [comment]
> Would it be an alright workaround if I just added a dependency-free wrapping routine here? It would duplicate code from the client repo slightly but would, I think, be the best solution.

Yep, that sounds good. We don't really ever need to wrap documents anytime except for translation, so it would make sense for the function to live here too and Connector and Client to use it from the shared repo.

**Comment by AbeJellinek** [comment]
Actually, though, `wrapDocument` is [defined in `example/http.js`](https://github.com/zotero/translate/blob/master/example/http.js#L191) in this repo, and I see that zotero-ios [also provides it](https://github.com/zotero/zotero-ios/blob/6870c0d937b3ee51676bb31eb3e01473f5f1b623/ZShare/Assets/translation/http.js#L176). Could we just make it a requirement, i.e. add a stub to `src/http.js` that throws a not implemented error? If it's _not_ a requirement, I think we should remove it from the example `http.js` (where it isn't currently used).

It does make some sense to have separate implementations between client and browser/iOS, at least, since the client has `Zotero.HTTP.Location` and `Zotero.HTTP.Window` and the browser has `new URL`.

**Comment by adomasven** [comment]
> Could we just make it a requirement, i.e. add a stub to src/http.js that throws a not implemented error?
>
> It does make some sense to have separate implementations between client and browser/iOS, at least, since the client has Zotero.HTTP.Location and Zotero.HTTP.Window and the browser has new URL.

Yep, I think you're right.

**Comment by adomasven** [comment]
Hmm, although I'm looking at translation server code now and it's using JSDOM, documents already come with the correct location attribute. Since this is translation specific and we can't know the implementation details of `HTTP.request()`, the wrapping should still happen here and be conditionally based on what is returned from `HTTP.request()`

**Comment by AbeJellinek** [comment]
OK, let me know if that does the trick.

**Pull request merged**
